### ISSUE TITLE
New logo for ArduinoMusicPlayer

### ISSUE THREAD

**Issue by reallinfo** [dandua98/ArduinoMusicPlayer#4]
I wanted to contribute to Arduino Music Player. I designed a logo for it. If you like it, I'll send you the files.

![amusicplayer](https://user-images.githubusercontent.com/36298335/38153316-bb41c5be-3474-11e8-8255-5edd1dfa0a90.jpg)

**Comment by dandua98** [comment]
Hi @reallinfo,

That looks amazing, would love to add it to the repository and our README. Feel free to fork the project and edit the README to add the logo at appropriate places! You can also add it to common/icons and I would edit the code to make this our boot screen later. Add yourself to a contributors section after Authors once you're done. 

Thank you for your help!

Best,
Danish

**Comment by reallinfo** [comment]
I'm glad you like it :) I sent pr. Please check it.

https://github.com/dandua98/ArduinoMusicPlayer/pull/5

**Comment by dandua98** [comment]
Pull request merged, I added you to contributors! I presume the name in your email (**Komiser Back**) is your real name so I used that, please let me know otherwise.

**Comment by reallinfo** [comment]
Yes, no problem. Thanks!
